BUG: increase precision
QIICR/dcmqi pull request #415
Opened 2021-01-27 16:47 UTC by fedorov

resolves #414

2021-02-02 18:48 UTC, rfloca commented on libsrc/Helper.cpp
> +    sstream << fixed << setprecision(15) << f;
sstream.imbue(std::locale::classic());
before using the sstream.

2021-02-02 18:50 UTC, rfloca commented on libsrc/Helper.cpp
> +    size_t dot_position = formatted_f.find('.');
You can move thin into the if statement as it is only used in that scope.

2021-02-02 18:52 UTC, rfloca commented on libsrc/Helper.cpp
> +    }
Should not be needed, if everything works according to standard. But it doesn't hurt, if you have no very high performance requirements.

2021-02-02 19:00 UTC, rfloca requested changes

2021-02-03 07:31 UTC, kislinsk commented
Here's my shot: http://cpp.sh/72ipr

To squeeze every little possible bit of precision out of it, you could print both scientific and fixed notation to strings and compare their lengths. If the scientific notation fits, use it. Fixed notation otherwise. The numeric_limits::max_digits10 ensures that both notations represent the maximum possible precision.

2021-02-03 08:42 UTC, kislinsk commented
Nevermind, I just noticed that DCMQI only used float so it makes things easier in the context of 16 characters. The standard library provides useful constants for serializing floating point numbers with maximum precision and for float (with all the extras) it always fits even into less than 16 characters. I will create a pull request for review.

2021-02-08 17:37 UTC, fedorov commented
replaced by #416

2021-02-08 17:37 UTC, closed without merging